"""Markdown report generator."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from collections import Counter

from .models import ScanState, Severity


def generate_report(state: ScanState, duration_seconds: float, output_dir: str) -> str:
    """Generate a markdown security assessment report."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    severity_counts = Counter(f.severity.value for f in state.findings)

    # Sort findings by severity
    severity_order = [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO]
    sorted_findings = sorted(state.findings, key=lambda f: severity_order.index(f.severity))

    lines = [
        "# Reaper Security Assessment Report",
        "",
        f"**Target:** {state.target}",
        f"**Date:** {now}",
        f"**Total Requests:** {state.request_count}",
        f"**Duration:** {duration_seconds / 60:.1f} minutes",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
    ]

    if not state.findings:
        lines.append("No exploitable vulnerabilities were confirmed during this assessment.")
        lines.append("This does not guarantee the application is secure — only that automated")
        lines.append("black-box testing did not find provable issues within the request budget.")
    else:
        summary_parts = []
        for sev in severity_order:
            count = severity_counts.get(sev.value, 0)
            if count:
                summary_parts.append(f"**{count} {sev.value}**")
        lines.append(f"Found {', '.join(summary_parts)} vulnerabilities.")
        lines.append("")

        # Severity breakdown table
        lines.append("| Severity | Count |")
        lines.append("|----------|-------|")
        for sev in severity_order:
            count = severity_counts.get(sev.value, 0)
            if count:
                lines.append(f"| {sev.value} | {count} |")

    lines.extend(["", "---", "", "## Findings", ""])

    for i, finding in enumerate(sorted_findings, 1):
        lines.extend([
            f"### {i}. [{finding.severity.value}] {finding.title}",
            "",
            f"**OWASP Category:** {finding.owasp_category}",
            f"**URL:** `{finding.url}`",
            "",
            "**Evidence:**",
            "",
            f"```",
            finding.evidence,
            "```",
            "",
            "**Reproduction:**",
            "",
            "```",
            finding.reproduction_steps,
            "```",
            "",
            f"**Remediation:** {finding.remediation}",
            "",
            "---",
            "",
        ])

    # Discovered attack surface
    lines.extend([
        "## Attack Surface Summary",
        "",
        f"- **Endpoints discovered:** {len(state.endpoints)}",
        f"- **Forms discovered:** {len(state.forms)}",
        f"- **Technologies identified:** {', '.join(state.technologies) if state.technologies else 'None detected'}",
        "",
    ])

    if state.endpoints:
        lines.extend(["### Endpoints", "", "| Method | URL | Status |", "|--------|-----|--------|"])
        for ep in state.endpoints[:50]:
            lines.append(f"| {ep.method} | `{ep.url}` | {ep.status_code} |")
        if len(state.endpoints) > 50:
            lines.append(f"| ... | *{len(state.endpoints) - 50} more* | |")
        lines.append("")

    lines.extend([
        "---",
        "",
        "## Methodology",
        "",
        "This assessment was performed using Reaper, an AI-driven black-box penetration testing tool.",
        "The tool operates autonomously through four phases:",
        "",
        "1. **Reconnaissance** — Crawling and mapping the application's attack surface",
        "2. **Analysis** — Identifying potential vulnerabilities across OWASP Top 10 categories",
        "3. **Exploitation** — Executing real attacks to prove vulnerabilities are exploitable",
        "4. **Reporting** — Compiling findings with evidence and reproduction steps",
        "",
        "Only vulnerabilities confirmed through successful exploitation are included in this report.",
        "",
        "---",
        "",
        "*Generated by Reaper v1.0*",
    ])

    report_text = "\n".join(lines)

    # Write to file
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    hostname = state.target.split("//")[-1].split("/")[0].split(":")[0]
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"reaper_report_{hostname}_{timestamp}.md"

    report_file = output_path / filename
    report_file.write_text(report_text, encoding="utf-8")

    return str(report_file)
